spring.application.name=Backend
server.port=8080
spring.datasource.url=jdbc:postgresql://auth-db.ci36u0yu444y.us-east-1.rds.amazonaws.com:5432/authentication
spring.datasource.username=postgres
spring.datasource.password=vinaypostgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=900000