spring.application.name=Backend
server.port=8080
spring.datasource.url=jdbc:postgresql://auth-db.ci36u0yu444y.us-east-1.rds.amazonaws.com:5432/authentication
spring.datasource.username=postgres
spring.datasource.password=vinaypostgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.org.hdfclife.backend=DEBUG

jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=900000

# Login Rate Limiting
login.rate-limit.user-limit=10
login.rate-limit.ip-limit=10
login.rate-limit.refresh-period-seconds=60


# Mock External Login Service
mock.login.url=http://localhost:8080/mock/external-login
mock.login.failure=false


# Login Circuit Breaker
login.circuit-breaker.failure-rate-threshold=50
login.circuit-breaker.minimum-number-of-calls=3
login.circuit-breaker.sliding-window-size=10
login.circuit-breaker.wait-duration-in-open-state-seconds=10
login.circuit-breaker.permitted-number-of-calls-in-half-open-state=2

jwt.refresh-expiration=604800000